### ISSUE TITLE
 Error with extensionRuntime API Proposal

### ISSUE THREAD

**Issue by brentdenboer** [opral/inlang-sherlock#20]
I am encountering an error with the plugin when clicking on project.inlang within the extension. Additionally, the plugin continuously loads without displaying any files or recommendations. I had previously used the plugin without issue on macOS, but I am experiencing difficulties on both Windows and Linux platforms.

This error message is displayed:

`Extension 'inlang.vs-code-extension' CANNOT use API proposal: extensionRuntime.
Its package.json#enabledApiProposals-property declares: [] but NOT extensionRuntime.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api inlang.vs-code-extension`
 
 I tried:
- Reinstalling VSCode
- Installing VSCode insiders
- Using an example project
- Reinstalling the plugin
- Switching VSCode profiles
- Using a different PC with Fedora instead of Windows
- Adding  `"enable-proposed-api": ["inlang.vs-code-extension"]` to argv.json
- Launching VSCode with `--enable-proposed-api inlang.vs-code-extension`

**Comment by felixhaeberle** [comment]
@brentdenboer Thanks for using our extension! <br><br>Can you share a minimal reproducible example project where this appears? <br><br>I can't reproduce it on my side. Also, I'm wondering why you tried the `--enable-proposed-api inlang.vs-code-extension` things, we do not make use of such a feature actively.

**Comment by felixhaeberle** [comment]
> Additionally, the plugin continuously loads without displaying any files or recommendations.

@brentdenboer Do you refer to the loading icon next to the Sherlock icon? This is a known issue an you can disable it simply by "hiding the badge".

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/0ab3708b-6143-449c-8d64-4d6eb33856ba/1b908cfa-298e-4dca-826b-9472c0036d67?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8wYWIzNzA4Yi02MTQzLTQ0OWMtOGQ2NC00ZDZlYjMzODU2YmEvMWI5MDhjZmEtMjk4ZS00ZGNhLTgyNmItOTQ3MmMwMDM2ZDY3IiwiaWF0IjoxNzEyOTEwOTIzLCJleHAiOjMzMjgzNDcwOTIzfQ.S9svcyZ7dYmAXm6wYV8GI7FCCXuBxLlz8IiuF0wEr-s " alt="Bildschirmfoto 2024-04-12 um 10.30.27.png" width="328" height="100" />

<br>This, weirdly, only appears when opening VS Code with the Sherlock tab open, not if you have it closed and open the extension tab afterwards.<br><br>If you mean something different, I'm interested in where you experience difficulties.

**Comment by brentdenboer** [comment]
> I'm wondering why you tried the `--enable-proposed-api inlang.vs-code-extension` things, we do not make use of such a feature actively.

I tried this because it was in the error message

I also fixed the issue, it was just an config error in the project.inlang directory

**Comment by felixhaeberle** [comment]
Cool! Happy you have it resolved!:)

**Comment by felixhaeberle** [comment]
@brentdenboer how did you resolve this? we have another user asking for this.

**Comment by brentdenboer** [comment]
I had only one languageTag set in the settings.json file

**Comment by Andriano24** [comment]
This is my settings.json file, I do have two language tags and I still have the same problem
```
{
  "$schema": "https://inlang.com/schema/project-settings",

  "sourceLanguageTag": "en",
  "languageTags": [
    "en",
    "el"
  ],
  "modules": [
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-t-function-matcher@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-without-source@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-missing-translation@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-snake-case-id@latest/dist/index.js",
    "https://cdn.jsdelivr.net/npm/@inlang/message-lint-rule-valid-js-identifier@latest/dist/index.js"
  ],
  "plugin.inlang.messageFormat": {
    "pathPattern": "./messages/{languageTag}.json"
  },
  "messageLintRuleLevels": {
    "messageLintRule.inlang.messageWithoutSource": "error",
    "messageLintRule.inlang.missingTranslation": "error",
    "messageLintRule.inlang.snakeCaseId": "error",
    "messageLintRule.inlang.validJsIdentifier": "error"
  }
}
```

**Comment by felixhaeberle** [comment]
@Andriano24 

```json
    "https://cdn.jsdelivr.net/npm/@inlang/plugin-m-function-matcher@latest/dist/index.js",
    "~~https://cdn.jsdelivr.net/npm/@inlang/plugin-t-function-matcher@latest/dist/index.js~~",
```

Can you try either/or but not both of them? You probably need the m function matcher if you are using paraglide, or the t function matcher if you are using another t function based syntax in code.

**Comment by felixhaeberle** [comment]
mmh, that's really strange. I'll debug this and come back to you!

**Comment by PlainBane** [comment]
I have the same issue. Linux VSCode/Codium 1.96.4. Changing settings.json does nothing.
